version: "3"
services:
  backend:
    build: ./
    command: pm2-runtime start ecosystem.config.js --env ${NODE_ENV}
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      REDIS_HOST: ${REDIS_HOST}
      API_ENDPOINT: ${GEO_ENDPOINT}
      API_TOKEN: ${GEO_KEY}
      JSON_TOKEN_SECRET: ${JSON_TOKEN_CHECK}
    volumes:
      - .:/app
    devices:
      - class/86E0D1E0-8089-11D0-9CE4-08003E301F73
    privileged: true
    ports:
      - 8080:8080
      - 9000:9000
    networks:
      - consentweb
    depends_on:
      - mysql
      - cache

  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports: 
      - 33061:3306
    networks:
      - consentweb
    volumes:
      - ${MYSQL_VOLUME_PATH}:/var/lib/mysql
    
  cache:
    image: redis
    ports: 
      - 6379:6379
    networks: 
      - consentweb
    volumes:
      - redis:/data
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - 8081:80
    depends_on:
      - mysql
    networks:
      - consentweb

volumes:
  cookiesdb:
  redis:
networks: 
  consentweb:
